package phonesimulator;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AveyBD
 */
public class Phonesimulator extends javax.swing.JPanel {

    /**
     * Creates new form Phonesimulator
     */
    JFrame frame;
    boolean call_1 = true;
    boolean call_2 = true;
    boolean call_3 = true;
    boolean call_4 = true;
    boolean call_5 = true;
    boolean call_6 = true;
    int calling[] = new int[7];
    int total_call = 0;
    int success_call = 0;
    int failed_call = 0;
    
    public Phonesimulator(JFrame frame){
        this.frame = frame;
        initComponents();
    }
    
    private static void createAndShowGUI() {
        //Create and set up the window.
        JFrame frame = new JFrame("Phone Call Simulator");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Create and set up the content pane.
        Phonesimulator newContentPane = new Phonesimulator(frame);
        newContentPane.setOpaque(true); //content panes must be opaque
        frame.setContentPane(newContentPane);

        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }
    
    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        call1 = new javax.swing.JButton();
        end1 = new javax.swing.JButton();
        call2 = new javax.swing.JButton();
        end2 = new javax.swing.JButton();
        call3 = new javax.swing.JButton();
        end3 = new javax.swing.JButton();
        call4 = new javax.swing.JButton();
        end4 = new javax.swing.JButton();
        call5 = new javax.swing.JButton();
        end5 = new javax.swing.JButton();
        call6 = new javax.swing.JButton();
        end6 = new javax.swing.JButton();
        phone1 = new javax.swing.JLabel();
        phone2 = new javax.swing.JLabel();
        phone3 = new javax.swing.JLabel();
        phone4 = new javax.swing.JLabel();
        phone5 = new javax.swing.JLabel();
        phone6 = new javax.swing.JLabel();
        status1 = new javax.swing.JLabel();
        status2 = new javax.swing.JLabel();
        status3 = new javax.swing.JLabel();
        status4 = new javax.swing.JLabel();
        status5 = new javax.swing.JLabel();
        status6 = new javax.swing.JLabel();
        totalsuccessllabel = new javax.swing.JLabel();
        totalfailedllabel = new javax.swing.JLabel();
        totalcallsllabel = new javax.swing.JLabel();
        success = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        clocktime = new javax.swing.JLabel();
        ClockTimeIn = new javax.swing.JTextField();
        totalcallsllabel1 = new javax.swing.JLabel();
        settime = new javax.swing.JButton();

        setName("mainpanel"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        call1.setText("Call");
        call1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call1ActionPerformed(evt);
            }
        });
        add(call1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, -1, -1));

        end1.setText("End");
        end1.setEnabled(false);
        end1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end1ActionPerformed(evt);
            }
        });
        add(end1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 53, -1, -1));

        call2.setText("Call");
        call2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call2ActionPerformed(evt);
            }
        });
        add(call2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 155, -1, -1));

        end2.setText("End");
        end2.setEnabled(false);
        end2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end2ActionPerformed(evt);
            }
        });
        add(end2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 193, -1, -1));

        call3.setText("Call");
        call3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call3ActionPerformed(evt);
            }
        });
        add(call3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 290, -1, -1));

        end3.setText("End");
        end3.setEnabled(false);
        end3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end3ActionPerformed(evt);
            }
        });
        add(end3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 328, -1, -1));

        call4.setText("Call");
        call4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call4ActionPerformed(evt);
            }
        });
        add(call4, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 15, -1, -1));

        end4.setText("End");
        end4.setEnabled(false);
        end4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end4ActionPerformed(evt);
            }
        });
        add(end4, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 53, -1, -1));

        call5.setText("Call");
        call5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call5ActionPerformed(evt);
            }
        });
        add(call5, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 155, -1, -1));

        end5.setText("End");
        end5.setEnabled(false);
        end5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end5ActionPerformed(evt);
            }
        });
        add(end5, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 193, -1, -1));

        call6.setText("Call");
        call6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                call6ActionPerformed(evt);
            }
        });
        add(call6, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 290, -1, -1));

        end6.setText("End");
        end6.setEnabled(false);
        end6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                end6ActionPerformed(evt);
            }
        });
        add(end6, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 328, -1, -1));

        phone1.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone1.setText("1");
        add(phone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 73, -1, -1));

        phone2.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone2.setText("2");
        add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 182, -1, -1));

        phone3.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone3.setText("3");
        add(phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 290, -1, -1));

        phone4.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone4.setText("4");
        add(phone4, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 73, -1, -1));

        phone5.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone5.setText("5");
        add(phone5, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 182, -1, -1));

        phone6.setFont(new java.awt.Font("Open Sans Extrabold", 0, 36)); // NOI18N
        phone6.setText("6");
        add(phone6, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 290, -1, -1));

        status1.setText("Ready");
        add(status1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 116, -1, -1));

        status2.setText("Ready");
        add(status2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 226, -1, -1));

        status3.setText("Ready");
        add(status3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 366, -1, -1));

        status4.setText("Ready");
        add(status4, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 116, -1, -1));

        status5.setText("Ready");
        add(status5, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 231, -1, -1));

        status6.setText("Ready");
        add(status6, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 366, -1, -1));

        totalsuccessllabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        totalsuccessllabel.setText("Total Successful Calls:");
        add(totalsuccessllabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        totalfailedllabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        totalfailedllabel.setText("Total Failed Calls:");
        add(totalfailedllabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        totalcallsllabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        totalcallsllabel.setText("Total Calls:");
        add(totalcallsllabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        success.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        success.setText("0");
        add(success, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 199, -1, -1));

        fail.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        fail.setText("0");
        add(fail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        total.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        total.setText("0");
        add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));

        clocktime.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        clocktime.setText("0000");
        add(clocktime, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, 20));

        ClockTimeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClockTimeInActionPerformed(evt);
            }
        });
        add(ClockTimeIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 139, 30));

        totalcallsllabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        totalcallsllabel1.setText("Clock Time:");
        add(totalcallsllabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, 30));

        settime.setText("Set Time");
        settime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settimeActionPerformed(evt);
            }
        });
        add(settime, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void call1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call1ActionPerformed
        Object possibilities[] = {"2", "3", "4", "5", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Number To Call",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "2");
        
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call2.setEnabled(false);
                end2.setEnabled(true);
                call_1= false;
                call_2 = false;
                calling[1] = 2;
                calling[2] = 1;
                status1.setText("In call with 2");
                status2.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_1= false;
                call_3 = false;
                calling[1] = 3;
                calling[3] = 1;
                status1.setText("In call with 3");
                status3.setText("In call with 1");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_1= false;
                call_4 = false;
                calling[1] = 4;
                calling[4] = 1;
                status1.setText("In call with 4");
                status4.setText("In call with 1");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_1= false;
                call_5 = false;
                calling[1] = 5;
                calling[5] = 1;
                status1.setText("In call with 5");
                status5.setText("In call with 1");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call1.setEnabled(false);
                end1.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_1= false;
                call_6 = false;
                calling[1] = 6;
                calling[6] = 1;
                status1.setText("In call with 6");
                status6.setText("In call with 1");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.                  
    }//GEN-LAST:event_call1ActionPerformed

    private void end1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end1ActionPerformed
        call1.setEnabled(true);
        end1.setEnabled(false);
        status1.setText("Ready");
        call_1 = true;
        if(calling[1] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[1] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[1] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[1] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[1] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end1ActionPerformed

    private void call2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call2ActionPerformed
        Object possibilities[] = {"1", "3", "4", "5", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_2= false;
                call_1 = false;
                calling[2] = 1;
                calling[1] = 2;
                status1.setText("In call with 2");
                status2.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_2= false;
                call_3 = false;
                calling[2] = 3;
                calling[3] = 2;
                status2.setText("In call with 3");
                status3.setText("In call with 2");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_2= false;
                call_4 = false;
                calling[2] = 4;
                calling[4] = 2;
                status2.setText("In call with 4");
                status4.setText("In call with 2");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_2= false;
                call_5 = false;
                calling[2] = 5;
                calling[5] = 2;
                status2.setText("In call with 5");
                status5.setText("In call with 2");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_2= false;
                call_6 = false;
                calling[2] = 6;
                calling[6] = 2;
                status2.setText("In call with 6");
                status6.setText("In call with 2");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call2ActionPerformed

    private void end2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end2ActionPerformed
        call2.setEnabled(true);
        end2.setEnabled(false);
        status2.setText("Ready");
        call_2 = true;
        if(calling[2] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }if(calling[2] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[2] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[2] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[2] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end2ActionPerformed

    private void call3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call3ActionPerformed
        Object possibilities[] = {"1", "2", "4", "5", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call3.setEnabled(false);
                end3.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_3= false;
                call_1 = false;
                calling[3] = 1;
                calling[1] = 3;
                status1.setText("In call with 3");
                status3.setText("In call with 1");
            }else if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_2= false;
                call_3 = false;
                calling[2] = 3;
                calling[3] = 2;
                status2.setText("In call with 3");
                status3.setText("In call with 2");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call3.setEnabled(false);
                end3.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_3= false;
                call_4 = false;
                calling[3] = 4;
                calling[4] = 3;
                status3.setText("In call with 4");
                status4.setText("In call with 3");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call3.setEnabled(false);
                end3.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_3= false;
                call_5 = false;
                calling[3] = 5;
                calling[5] = 3;
                status3.setText("In call with 5");
                status5.setText("In call with 3");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call3.setEnabled(false);
                end3.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_3= false;
                call_6 = false;
                calling[3] = 6;
                calling[6] = 3;
                status3.setText("In call with 6");
                status6.setText("In call with 3");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call3ActionPerformed

    private void end3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end3ActionPerformed
        call3.setEnabled(true);
        end3.setEnabled(false);
        status3.setText("Ready");
        call_3 = true;
        if(calling[3] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }if(calling[3] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[3] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[3] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[3] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end3ActionPerformed

    private void call4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call4ActionPerformed
        Object possibilities[] = {"1", "2", "3", "5", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call4.setEnabled(false);
                end4.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_4= false;
                call_1 = false;
                calling[4] = 1;
                calling[1] = 4;
                status1.setText("In call with 4");
                status4.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call4.setEnabled(false);
                end4.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_4= false;
                call_3 = false;
                calling[4] = 3;
                calling[3] = 4;
                status4.setText("In call with 3");
                status3.setText("In call with 4");
            }else if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_2= false;
                call_4 = false;
                calling[2] = 4;
                calling[4] = 2;
                status2.setText("In call with 4");
                status4.setText("In call with 2");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call4.setEnabled(false);
                end4.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_4= false;
                call_5 = false;
                calling[4] = 5;
                calling[5] = 4;
                status4.setText("In call with 5");
                status5.setText("In call with 4");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call4.setEnabled(false);
                end4.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_4= false;
                call_6 = false;
                calling[4] = 6;
                calling[6] = 4;
                status4.setText("In call with 6");
                status6.setText("In call with 4");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call4ActionPerformed

    private void end4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end4ActionPerformed
        call4.setEnabled(true);
        end4.setEnabled(false);
        status4.setText("Ready");
        call_4 = true;
        if(calling[4] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }if(calling[4] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[4] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[4] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[4] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end4ActionPerformed

    private void call5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call5ActionPerformed
        Object possibilities[] = {"1", "2", "3", "4", "6"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call5.setEnabled(false);
                end5.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_5= false;
                call_1 = false;
                calling[5] = 1;
                calling[1] = 5;
                status1.setText("In call with 5");
                status5.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call5.setEnabled(false);
                end5.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_5= false;
                call_3 = false;
                calling[5] = 3;
                calling[3] = 5;
                status5.setText("In call with 3");
                status3.setText("In call with 5");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call5.setEnabled(false);
                end5.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_5= false;
                call_4 = false;
                calling[5] = 4;
                calling[4] = 5;
                status5.setText("In call with 4");
                status4.setText("In call with 5");
            }else if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_2= false;
                call_5 = false;
                calling[2] = 5;
                calling[5] = 2;
                status2.setText("In call with 5");
                status5.setText("In call with 2");
            }else if("6".matches(s) && call_6){
                success_call++;
                success.setText(Integer.toString(success_call));
                call5.setEnabled(false);
                end5.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_5= false;
                call_6 = false;
                calling[5] = 6;
                calling[6] = 5;
                status5.setText("In call with 6");
                status6.setText("In call with 5");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call5ActionPerformed

    private void end5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end5ActionPerformed
        call5.setEnabled(true);
        end5.setEnabled(false);
        status5.setText("Ready");
        call_5 = true;
        if(calling[5] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[5] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[5] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[5] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }if(calling[5] == 6){
            call_6 = true;
            status6.setText("Ready");
            call6.setEnabled(true);
            end6.setEnabled(false);
        }
    }//GEN-LAST:event_end5ActionPerformed

    private void call6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_call6ActionPerformed
        Object possibilities[] = {"1", "2", "3", "4", "5"}; 
        String s = (String)JOptionPane.showInputDialog(
                                        frame,
                                        "Select phone number to dial",
                                        "Select...",
                                        JOptionPane.PLAIN_MESSAGE,
                                        null,
                                        possibilities,
                                        "1");
                
        //If a string was returned, say so.
        if ((s != null) && (s.length() > 0)) {
            total_call++;
            total.setText(Integer.toString(total_call));
            if("1".matches(s) && call_1){
                success_call++;
                success.setText(Integer.toString(success_call));
                call6.setEnabled(false);
                end6.setEnabled(true);
                call1.setEnabled(false);
                end1.setEnabled(true);
                call_6= false;
                call_1 = false;
                calling[6] = 1;
                calling[1] = 6;
                status1.setText("In call with 6");
                status6.setText("In call with 1");
            }else if("3".matches(s) && call_3){
                success_call++;
                success.setText(Integer.toString(success_call));
                call6.setEnabled(false);
                end6.setEnabled(true);
                call3.setEnabled(false);
                end3.setEnabled(true);
                call_6= false;
                call_3 = false;
                calling[6] = 3;
                calling[3] = 6;
                status6.setText("In call with 3");
                status3.setText("In call with 6");
            }else if("4".matches(s) && call_4){
                success_call++;
                success.setText(Integer.toString(success_call));
                call6.setEnabled(false);
                end6.setEnabled(true);
                call4.setEnabled(false);
                end4.setEnabled(true);
                call_6= false;
                call_4 = false;
                calling[6] = 4;
                calling[4] = 6;
                status6.setText("In call with 4");
                status4.setText("In call with 6");
            }else if("5".matches(s) && call_5){
                success_call++;
                success.setText(Integer.toString(success_call));
                call6.setEnabled(false);
                end6.setEnabled(true);
                call5.setEnabled(false);
                end5.setEnabled(true);
                call_6= false;
                call_5 = false;
                calling[6] = 5;
                calling[5] = 6;
                status6.setText("In call with 5");
                status5.setText("In call with 6");
            }else if("2".matches(s) && call_2){
                success_call++;
                success.setText(Integer.toString(success_call));
                call2.setEnabled(false);
                end2.setEnabled(true);
                call6.setEnabled(false);
                end6.setEnabled(true);
                call_2= false;
                call_6 = false;
                calling[2] = 6;
                calling[6] = 2;
                status2.setText("In call with 6");
                status6.setText("In call with 2");
            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "The subscriber is busy, please try again later!", "Busy", javax.swing.JOptionPane.ERROR_MESSAGE);
                failed_call++;
                fail.setText(Integer.toString(failed_call));
            }
            return;
        }//If you're here, the return value was null/empty.
    }//GEN-LAST:event_call6ActionPerformed

    private void end6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_end6ActionPerformed
        call6.setEnabled(true);
        end6.setEnabled(false);
        status6.setText("Ready");
        call_6 = true;
        if(calling[6] == 2){
            call_2 = true;
            status2.setText("Ready");
            call2.setEnabled(true);
            end2.setEnabled(false);
        }if(calling[6] == 3){
            call_3 = true;
            status3.setText("Ready");
            call3.setEnabled(true);
            end3.setEnabled(false);
        }if(calling[6] == 4){
            call_4 = true;
            status4.setText("Ready");
            call4.setEnabled(true);
            end4.setEnabled(false);
        }if(calling[6] == 5){
            call_5 = true;
            status5.setText("Ready");
            call5.setEnabled(true);
            end5.setEnabled(false);
        }if(calling[6] == 1){
            call_1 = true;
            status1.setText("Ready");
            call1.setEnabled(true);
            end1.setEnabled(false);
        }
    }//GEN-LAST:event_end6ActionPerformed

    private void ClockTimeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClockTimeInActionPerformed
       double N1 = Float.parseFloat (ClockTimeIn.getText());
    }//GEN-LAST:event_ClockTimeInActionPerformed

    private void settimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settimeActionPerformed
        String N1 = (ClockTimeIn.getText());
        clocktime.setText(N1);    
    }//GEN-LAST:event_settimeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ClockTimeIn;
    private javax.swing.JButton call1;
    private javax.swing.JButton call2;
    private javax.swing.JButton call3;
    private javax.swing.JButton call4;
    private javax.swing.JButton call5;
    private javax.swing.JButton call6;
    private javax.swing.JLabel clocktime;
    private javax.swing.JButton end1;
    private javax.swing.JButton end2;
    private javax.swing.JButton end3;
    private javax.swing.JButton end4;
    private javax.swing.JButton end5;
    private javax.swing.JButton end6;
    private javax.swing.JLabel fail;
    private javax.swing.JLabel phone1;
    private javax.swing.JLabel phone2;
    private javax.swing.JLabel phone3;
    private javax.swing.JLabel phone4;
    private javax.swing.JLabel phone5;
    private javax.swing.JLabel phone6;
    private javax.swing.JButton settime;
    private javax.swing.JLabel status1;
    private javax.swing.JLabel status2;
    private javax.swing.JLabel status3;
    private javax.swing.JLabel status4;
    private javax.swing.JLabel status5;
    private javax.swing.JLabel status6;
    private javax.swing.JLabel success;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalcallsllabel;
    private javax.swing.JLabel totalcallsllabel1;
    private javax.swing.JLabel totalfailedllabel;
    private javax.swing.JLabel totalsuccessllabel;
    // End of variables declaration//GEN-END:variables
}
